# Generated by Django 4.1.7 on 2023-03-13 19:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_level', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ThisClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('date', models.DateField(null=True)),
                ('time', models.TimeField(null=True)),
                ('title', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.CharField(max_length=50)),
                ('classes_attending', models.ManyToManyField(related_name='class_attending', through='live2learnapi.Student', to='live2learnapi.thisclass')),
                ('classes_teaching', models.ManyToManyField(related_name='class_teaching', through='live2learnapi.Instructor', to='live2learnapi.thisclass')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='thisclass',
            name='instructor',
            field=models.ManyToManyField(related_name='class_instructor', through='live2learnapi.Instructor', to='live2learnapi.userprofile'),
        ),
        migrations.AddField(
            model_name='thisclass',
            name='skill',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='live2learnapi.skill'),
        ),
        migrations.AddField(
            model_name='thisclass',
            name='students',
            field=models.ManyToManyField(related_name='class_students', through='live2learnapi.Student', to='live2learnapi.userprofile'),
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=55)),
                ('this_class', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='live2learnapi.thisclass')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='this_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_class', to='live2learnapi.thisclass'),
        ),
        migrations.AddField(
            model_name='student',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student', to='live2learnapi.userprofile'),
        ),
        migrations.AddField(
            model_name='instructor',
            name='this_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructor_class', to='live2learnapi.thisclass'),
        ),
        migrations.AddField(
            model_name='instructor',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructor', to='live2learnapi.userprofile'),
        ),
    ]
