# Generated by Django 4.1.7 on 2023-03-15 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('live2learnapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thisclass',
            old_name='instructor',
            new_name='instructors',
        ),
        migrations.AlterField(
            model_name='tag',
            name='this_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='live2learnapi.thisclass'),
        ),
    ]
